_GLOSSARY = {
    "registry": "包下载源地址",
    "prefix": "全局安装目录",
    "cache": "缓存存储目录",
    "proxy": "HTTP 代理地址",
    "https-proxy": "HTTPS 代理地址",
    "http-proxy": "HTTP 代理地址",
    "strict-ssl": "要求有效的 SSL 证书",
    "save": "安装时保存到 package.json",
    "save-exact": "安装精确版本，不带 ^~ 前缀",
    "package-lock": "生成 package-lock.json 锁文件",
    "ignore-scripts": "跳过生命周期脚本（pre/post install）",
    "audit": "安装时运行漏洞审计",
    "fund": "安装时显示资助信息",
    "loglevel": "日志详细程度",
    "depth": "依赖树展示深度",
    "tag": "安装时默认的 dist-tag",
    "global": "全局模式操作",
    "init-version": "npm init 时的初始版本号",
    "init-license": "npm init 时的默认许可证",
    "userconfig": "用户级配置文件路径",
    "globalconfig": "全局配置文件路径",
    "editor": "默认编辑器",
    "shell": "脚本执行使用的 Shell",
    "node-options": "Node.js 命令行参数",
    "python": "node-gyp 使用的 Python 路径",
    "version": "包/工具版本号",
    "HOME": "用户主目录",
    "PREFIX": "安装前缀路径",
    "user.name": "Git 提交者姓名",
    "user.email": "Git 提交者邮箱",
    "core.autocrlf": "行尾转换模式（true/input/false）",
    "core.sshCommand": "远程操作使用的 SSH 命令",
    "core.proxy": "Git HTTP 代理",
    "core.longpaths": "Windows 上支持超过 260 字符的长路径",
    "core.excludesfile": "全局 gitignore 文件路径",
    "init.defaultBranch": "新仓库的默认分支名",
    "init.defaultBranch.main": "默认分支设为 main",
    "pull.rebase": "拉取时使用 rebase 而非 merge",
    "fetch.prune": "拉取时清理已删除的远程分支",
    "remote.origin.url": "远程仓库地址",
    "remote.origin.fetch": "git fetch 的引用规格",
    "branch.main.remote": "分支的上游远程名",
    "branch.main.merge": "分支的上游跟踪分支",
    "localRepository": "本地构件存储路径",
    "settings.xml": "Maven 配置文件",
    "bin": "可执行文件目录",
    "config.toml": "Cargo 配置文件",
    "GOROOT": "Go 安装根目录",
    "GOPATH": "Go 工作空间目录",
    "GOBIN": "Go 二进制安装目录",
    "GOOS": "目标操作系统",
    "GOARCH": "目标架构",
    "GOMODCACHE": "模块缓存目录",
    "GOCACHE": "构建缓存目录",
    "GOPROXY": "模块代理地址",
    "GONOSUMCHECK": "跳过校验和的模块",
    "GOPRIVATE": "不走代理/校验库的私有模块",
    "GONOPROXY": "绕过代理的模块",
    "active_prefix": "当前激活的环境路径",
    "conda_prefix": "Conda 安装根目录",
    "envs_dirs": "环境目录列表",
    "pkgs_dirs": "包缓存目录列表",
    "channels": "包来源频道",
    "default_prefix": "默认环境前缀",
    "ssl_verify": "SSL 证书验证设置",
    "auto_activate_base": "Shell 启动时自动激活 base 环境",
    "JAVA_HOME": "JDK 安装目录",
    "JRE_HOME": "JRE 安装目录",
    "JDK_HOME": "JDK 安装目录",
    "CLASSPATH": "Java 类搜索路径",
    "PYTHONHOME": "Python 安装前缀目录",
    "PYTHONPATH": "Python 模块搜索路径",
    "PYTHONSTARTUP": "交互模式启动脚本",
    "PYTHONIOENCODING": "标准输入输出编码",
    "PYTHONUTF8": "启用 UTF-8 模式",
    "PIP_INDEX_URL": "PyPI 镜像源地址",
    "PIP_TARGET": "安装目标目录",
    "NODE_HOME": "Node.js 安装目录",
    "NODE_PATH": "Node.js 模块搜索路径",
    "NPM_CONFIG_PREFIX": "npm 全局安装前缀",
    "NPM_CONFIG_REGISTRY": "npm 仓库源地址",
    "CARGO_HOME": "Cargo 工作空间根目录",
    "RUSTUP_HOME": "Rustup 工具链目录",
    "ANDROID_HOME": "Android SDK 根目录",
    "ANDROID_SDK_ROOT": "Android SDK 根目录（备用）",
    "DOCKER_HOST": "Docker 守护进程连接地址",
    "HTTP_PROXY": "HTTP 代理（全局）",
    "HTTPS_PROXY": "HTTPS 代理（全局）",
    "NO_PROXY": "不走代理的主机列表",
    "GRADLE_USER_HOME": "Gradle 配置与缓存目录",
    "M2_HOME": "Maven 安装目录",
    "MAVEN_HOME": "Maven 安装目录",
    "VCPKG_ROOT": "vcpkg 安装根目录",
    "CONAN_HOME": "Conan 缓存目录",
    "GIT_HOME": "Git 安装目录",
    "GIT_EXEC_PATH": "Git 可执行文件路径",
    "GIT_EDITOR": "Git 默认编辑器",
    "DOCKER_CONFIG": "Docker 配置目录",
    "COMPOSE_FILE": "docker-compose 文件路径",
    "ANT_HOME": "Ant 安装目录",
    "GRADLE_HOME": "Gradle 安装目录",
    "POETRY_HOME": "Poetry 安装目录",
    "CONDA_DEFAULT_ENV": "当前 Conda 环境名",
    "CONDA_PREFIX": "当前 Conda 环境路径",
    "VIRTUAL_ENV": "当前 Python 虚拟环境路径",
    "PATHEXT": "Windows 可执行文件扩展名列表",
    "COMSPEC": "Windows 命令解释器路径",
}


def get_description(key: str) -> str:
    return _GLOSSARY.get(key, "")
